services:
  # PostgreSQL Database
  postgres:
    image: postgres:17-alpine
    container_name: propel-postgres
    environment:
      POSTGRES_DB: propel
      POSTGRES_USER: propel_user
      POSTGRES_PASSWORD: propel_password
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - propel-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U propel_user -d propel"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # Redis Cache
  redis:
    image: redis:7.2
    container_name: propel-redis
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - propel-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # Redis Commander for managing Redis
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: propel-redis-commander
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8090:8080"
    networks:
      - propel-network
    depends_on:
      - redis


  # Propel Demo
  propel.demo.api:
    image: ${DOCKER_REGISTRY-}propel-demo-api
    container_name: propel-demo-api
    build:
      context: .
      dockerfile: usage-demo/Propel.ClientApi/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080 
      - POSTGRES_DB=propel
      - POSTGRES_USER=propel_user
      - POSTGRES_PASSWORD=propel_password
      - REDIS_PASSWORD=
    ports:
      - "5002:8080"
    networks:
      - propel-network
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./usage-demo/Propel.ClientApi/appsettings.json
        target: /app/appsettings.json
        read_only: true

  # Propel Management Api
  propel.management.api:
    image: ${DOCKER_REGISTRY-}propel-flagsmanagement-api
    container_name: propel-flagsmanagement-api
    build:
      context: .
      dockerfile: ui/Propel.FlagsManagement.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080 
      - POSTGRES_DB=propel
      - POSTGRES_USER=propel_user
      - POSTGRES_PASSWORD=propel_password
      - REDIS_PASSWORD=
    ports:
      - "5003:8080"
    networks:
      - propel-network
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./ui/Propel.FlagsManagement.Api/appsettings.json
        target: /app/appsettings.json
        read_only: true

  # Propel Management UI
  propel.management.website:
    image: ${DOCKER_REGISTRY-}propel-flagsmanagement-website
    container_name: propel-flagsmanagement-website
    build:
      context: .
      dockerfile: ui/Propel.FlagsManagement.Website/Dockerfile
    ports:
      - "3000:80"
    networks:
      - propel-network
    depends_on:
      - propel.management.api
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:5003/api

volumes:
  postgres_data:
  redis_data:

networks:
  propel-network:
    driver: bridge

