name: Build and Test

on:
  push:
    branches: [ main ]
    paths:
      - '**/*.cs'
      - '**/*.csproj'
      - '**/*.sln'
      - '**/*.config'
      - '**/Directory.Build.props'
      - '**/Directory.Build.targets'
      - 'global.json'
      - 'nuget.config'
      - '.github/workflows/build.yml'
  pull_request:
    branches: [ main ]
    paths:
      - '**/*.cs'
      - '**/*.csproj'
      - '**/*.sln'
      - '**/*.config'
      - '**/Directory.Build.props'
      - '**/Directory.Build.targets'
      - 'global.json'
      - 'nuget.config'
      - '.github/workflows/build.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: | 
          9.0.x
          8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: dotnet test --configuration Release --no-build --verbosity normal